name: Build and Publish Image to GitHub Container Registry

on:
  # trigger manual
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'FPPSongInfo/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          source-url: https://nuget.pkg.github.com/jeffu231/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Display dotnet version
        run: dotnet --version
      - name: Install Dependencies
        run: dotnet restore

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish and push the container Image
        run: |
          dotnet publish -c Release /p:PublishProfile=github
