<Project Sdk="Microsoft.NET.Sdk.Worker">

		<PropertyGroup>
				<OutputType>Exe</OutputType>
				<TargetFramework>net10.0-windows</TargetFramework>
				<ImplicitUsings>enable</ImplicitUsings>
				<Nullable>enable</Nullable>
				<AnalysisLevel>latest</AnalysisLevel>
				<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
				<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
				<RootNamespace>FPPSongInfo</RootNamespace>
				<PublishSingleFile Condition="'$(Configuration)' == 'Release'">true</PublishSingleFile>
				<RuntimeIdentifier>win-x64</RuntimeIdentifier>
				<PlatformTarget>x64</PlatformTarget>
				<Version>1.2.0</Version>
				<RepositoryUrl>https://github.com/jeffu231/FPPSongInfo</RepositoryUrl>
				<Description>A consumer that listens for MQTT messages about the playing media and writes it to a simple file.</Description>
				<Authors>Jeff Uchitjil</Authors>
		</PropertyGroup>

		<ItemGroup>
				<InternalsVisibleTo Include="FPPSongInfo.Tests" />
				<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.10" />
				<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
				<PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.10" />
				<PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="10.0.10" />
				<PackageReference Include="MQTTnet" Version="4.3.7.1207" />
				<PackageReference Include="MQTTnet.Extensions.ManagedClient" Version="4.3.7.1207" />
		</ItemGroup>

</Project>
